code4romania/asset-declarations

- project_template/forms.py
- project_template/tasks.py
> add #16, asking for line count in 'Bunuri mobile'

- project_template/forms.py
- project_template/tasks.py
> Fix naming consistency in tasks.py, forms.py

- project_template/forms.py
- project_template/tasks.py
- project_template/templates/tasks/general_information_task.html
- project_template/templates/tasks/owned_buildings_task.html
Fixes #4 
Mistakenly deleted the branch and had to re-do the pull request.
It should all be OK now
> Fixes #4 - add task: owned buildings

- project_template/forms.py
- project_template/tasks.py
> add row count task #18 for Bank accounts

- project_template/templates/base.html
- project_template/templates/home.html
- project_template/templates/task.html
* Remove favicon tags since we have no favicon.
* Remove header blocks since we have no header.
* Small improvement to task page - remove padding from presenter.
> HTML refactoring.

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
- project_template/templates/tasks/owned_jewelry.html
Add task, template and form for adding precious metals and jewelry goods to the asset declaration microtasks
> Fix for #74 - Bunuri metale pretioase & bijuterii

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
- project_template/templates/tasks/owned_extra_valuable.html
Fix for #75 - [MICROTASK] Introducere informatii rand tabel III. Bunuri mobile - valorea depaseste 3000EUR
> Fix for #75 - Extra valuable/Estranged goods

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
- project_template/templates/tasks/owned_gifts_spouse.html
Fixes #80 
- re-ordered imports
- added the fields for the issue
- added missing "name_source_of_goods" field
- re-arranged the rows in the modified table entry to be pep-8 compliant
- added the task for the issue
- added HTML template page for the issue
> Add OwnedGoodsOrServicesPerSpouse, fixes #80

- project_template/templates/tasks/agricultural_activity.html
- project_template/templates/tasks/owned_automobile.html
- project_template/templates/tasks/owned_bank_accounts.html
- project_template/templates/tasks/owned_debts.html
- project_template/templates/tasks/owned_extra_valuable.html
- project_template/templates/tasks/owned_income_from_pensions.html
- project_template/templates/tasks/owned_jewelry.html
- project_template/templates/tasks/owned_land.html
Fixes #124 
Use English for variable naming - change the name of `nr_rand` in all template files
> Refactor the usage of variables in templates

- project_template/constants.py
- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
This is still WIP.
Not to be merged yet.
> Update the datamodels for the project

- project_template/forms.py
- project_template/tasks.py
- project_template/templates/tasks/owned_investments.html
> Added income from investments table rows and details tasks

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
- project_template/templates/tasks/owned_income_from_salaries.html
> Adding form for salary income

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
Fix owned building task fields
Closes code4romania/catpol-declaratii#140
> Add taxable value fields to the owned building and land tables

- project_template/templates/tasks/row_count_template.html
> Add text to explain edge cases with more than one value per row

- project_template/templates/tasks/owned_income_from_pensions.html
Fixes #85 
The code for income from pensions seems to be there already, so this is just the finishing touch
> Change text for pensions income to match the rest

- project_template/models.py
- project_template/tasks.py
> Fix mismatches between forms and models

- project_template/forms.py
> Move calculation of year choices

- project_template/models.py
> Add person foreign key for tasks missing this info

- project_template/models.py
Make all `share_ratio` fields have `max_digits=5, decimal_places=2`
> Fix issue #175

- project_template/forms.py
- project_template/models.py
- project_template/tasks.py
Make all all forms except TranscribeInitialInformation import the fields from the relevant Model.
> Refactor model forms

- .env
- Dockerfile
- catpol-dependencies/Dockerfile
- database.env
- docker-compose.yml
- docker-entrypoint
- project_template/settings/base.py
- project_template/settings/dev.py
- project_template/settings/production.py
- project_template/settings/stage.py
- requirements-dev.txt
- requirements-prod.txt
- requirements.txt
Just some small docker and setup improvements that I found during my initial setup.
I really loved using docker and docker-compose, so thank you for the setup 🙇 
The only problems that I had were with the database that was initialing before the web container, making the web container unable to start. I've added [dockerize](https://github.com/jwilder/dockerize), that has some nice features (from templates rendering to wait for a certain service to be up) and now the web container waits until the database is up and running.
Furthermore, I've pinned the dependencies (for reproducible builds, since installing the latest version all the time can break stuff), added [django-environ](https://github.com/joke2k/django-environ) thus making env related config really easy and following that, I've …
> Small docker improvements

- README.md
> Update README to reflect hiatus
